### ISSUE TITLE
Task - Find data libraries that include hoops and backboards.

### ISSUE THREAD

**Issue by dleerssen** [Allen-ISD-Computer-Science/REPO_BasketballTrainer_2024#30]
Support Story #20

**Comment by SeanM-007** [comment]
I know I'm late I just now saw this but more specially like what's the hoop for   like is UI or for the ui to learn because I'm kind of confused of what I'm looking for exactly

**Comment by SeanM-007** [comment]
(https://github.com/chonyy/basketball-shot-detection/blob/master/basketball_trace.jpg)

**Comment by SeanM-007** [comment]
https://github.com/avishah3/AI-Basketball-Shot-Detection-Tracker                                           


I found other things more so websites but they're not libraries and unsure if we should use them


The reason I didn't commit is one: I didn't merge or download the program to commit at home and I simply did research on how the detection software works by watching videos and learning about it and messing with to figure out how to use it as I want try see if I can train it on using the datasets

**Comment by TahmidR2456** [comment]
https://hoopr.sportsdataverse.org/

**Comment by SeanM-007** [comment]
https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

**Comment by SeanM-007** [comment]
I'm working on the video recording I was assigned to do and just also working on learning OpenCV and pose as I don't have much of an idea on how to install how it works opposed to Yolov8
