### ISSUE TITLE
setup VSCode with every group member

### ISSUE THREAD

**Issue by dleerssen** [Allen-ISD-Computer-Science/REPO_BasketballTrainer_2024#32]

**Comment by dleerssen** [comment]
Stuck. Could not update Anaconda correctly and was unable to setup VSCode properly.

**Comment by SeanM-007** [comment]
I did it

**Comment by AravLohe** [comment]
Done

**Comment by TahmidR2456** [comment]
Done

**Comment by SeanM-007** [comment]
I didn't commit because I don't have anything currently assigned to me so instead i've spent that time understanding how Anaconda and vscode works, researching how camera detection and object detection, and lastly just exploring OpenCV.

**Comment by dleerssen** [comment]
finished
